server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: xde-kenel
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/yhd_local?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: 123456

  redis:
    port: 6379
    password: root
    host: 127.0.0.1
    database: 11
  data:
    mongodb:
#      uri: mongodb://root(userName):root(password)@localhost(ip地址):27017(端口号)
      uri: mongodb://admin:123456@localhost:27027
      database: logs
      authentication-database: admin

logging:
  level:
    org.springframework.web.servlet.mvc: trace

# 天翼云
tianyiyun:
  accessId: d2aaab960d389a44e652
  secret: ce4ab893a611b88310a6db68b7997e589674faa9
  entpoints: http://oos-cn.ctyunapi.cn
  bucket: xiaode